"""Build NLI entailment matrix across (claim, evidence, alternatives). AWP core."""
from __future__ import annotations

from dataclasses import dataclass
from typing import List, Tuple

from hallucination_guard.trust_score import EvidenceItem
from hallucination_guard.text.adversarial_generator import AdversarialHypothesis


@dataclass
class MatrixRow:
    hypothesis: str
    evidence_text: str
    entailment: float
    contradiction: float
    neutral: float
    is_adversarial: bool
    # claim_text is stored for reference but not used in AWP scoring
    claim_text: str = ""


def build_matrix(
    claim_text: str,
    evidence: List[EvidenceItem],
    adversarial: List[AdversarialHypothesis],
    batch_size: int = 8,
) -> List[MatrixRow]:
    """Build an NLI entailment matrix for claim + evidence + adversarial hypotheses.

    For each (hypothesis, evidence_text) pair the NLI model predicts:
      entailment, contradiction, neutral probabilities.

    Original claim rows: is_adversarial=False
    Adversarial hypothesis rows: is_adversarial=True

    Parameters
    ----------
    claim_text   : The original claim being evaluated.
    evidence     : EvidenceItems from the shared pool.
    adversarial  : AdversarialHypothesis objects generated by the Prosecutor.
    batch_size   : NLI inference batch size (default 8 from settings).

    Returns
    -------
    List of MatrixRow, one per (hypothesis, evidence) pair.
    """
    import hallucination_guard.models.model_hub as hub_module
    hub = hub_module.hub

    # Build (hypothesis, evidence_text, is_adversarial) triples
    pairs: List[Tuple[str, str, bool]] = []
    for ev in evidence:
        ev_text = ev.text.strip()[:200]
        pairs.append((claim_text, ev_text, False))

    for adv in adversarial:
        hyp_text = adv.text
        for ev in evidence:
            ev_text = ev.text.strip()[:200]
            pairs.append((hyp_text, ev_text, True))

    if not pairs:
        return []

    # Build NLI input list: (premise=evidence, hypothesis=claim/adversarial)
    nli_inputs = [(ev_text, hyp) for hyp, ev_text, _ in pairs]

    # Batch inference
    nli_results = hub.nli.predict_batch(nli_inputs)

    rows: List[MatrixRow] = []
    for (hyp_text, ev_text, is_adv), nli in zip(pairs, nli_results):
        rows.append(MatrixRow(
            hypothesis=hyp_text,
            evidence_text=ev_text,
            entailment=nli.entailment,
            contradiction=nli.contradiction,
            neutral=nli.neutral,
            is_adversarial=is_adv,
            claim_text=claim_text,
        ))

    return rows
