"""Build NLI entailment matrix across (claim, evidence, alternatives). AWP core."""
from __future__ import annotations

import asyncio
from dataclasses import dataclass
from typing import List, Tuple

from hallucination_guard.trust_score import EvidenceItem
from hallucination_guard.text.adversarial_generator import AdversarialHypothesis


@dataclass
class MatrixRow:
    hypothesis: str
    evidence_text: str
    entailment: float
    contradiction: float
    neutral: float
    is_adversarial: bool
    # claim_text is stored for reference but not used in AWP scoring
    claim_text: str = ""


# Minimum NLI signal for an evidence item to be considered ON-TOPIC for the
# original claim.  An item whose original-claim row is dominated by "neutral"
# (i.e. max(entailment, contradiction) < this floor) does not bear on the
# claim's truth — it is topically related noise (e.g. a fact-check of an
# unrelated quote by the same entity).  Such items must be excluded from AWP
# scoring on BOTH sides: kept in, they (a) crush the averaged original_support
# and (b) hand the adversarial hypotheses a spurious high entailment, which is
# what drove true claims to REFUTED.  See diagnosis 2026-05-30.
RELEVANCE_MIN_SIGNAL: float = 0.15


def relevant_evidence_texts(
    rows: List["MatrixRow"],
    min_signal: float = RELEVANCE_MIN_SIGNAL,
) -> set:
    """Return the set of evidence_texts that actually bear on the claim.

    Relevance is judged from each evidence item's ORIGINAL-claim row
    (is_adversarial=False): the item is on-topic only if it meaningfully
    entails or contradicts the claim (max(entailment, contradiction) above
    the floor).  Neutral-dominated items carry no signal and are dropped.
    """
    return {
        getattr(r, "evidence_text", "")
        for r in rows
        if not r.is_adversarial
        and max(r.entailment, r.contradiction) >= min_signal
    }


async def build_matrix(
    claim_text: str,
    evidence: List[EvidenceItem],
    adversarial: List[AdversarialHypothesis],
    batch_size: int = 8,
) -> List[MatrixRow]:
    """Build an NLI entailment matrix for claim + evidence + adversarial hypotheses.

    For each (hypothesis, evidence_text) pair the NLI model predicts:
      entailment, contradiction, neutral probabilities.

    Original claim rows: is_adversarial=False
    Adversarial hypothesis rows: is_adversarial=True

    Parameters
    ----------
    claim_text   : The original claim being evaluated.
    evidence     : EvidenceItems from the shared pool.
    adversarial  : AdversarialHypothesis objects generated by the Prosecutor.
    batch_size   : NLI inference batch size (default 8 from settings).

    Returns
    -------
    List of MatrixRow, one per (hypothesis, evidence) pair.
    """
    import hallucination_guard.models.model_hub as hub_module
    hub = hub_module.hub

    # Build (hypothesis, evidence_text, is_adversarial) triples
    pairs: List[Tuple[str, str, bool]] = []
    for ev in evidence:
        ev_text = ev.text.strip()[:200]
        pairs.append((claim_text, ev_text, False))

    for adv in adversarial:
        hyp_text = adv.text
        for ev in evidence:
            ev_text = ev.text.strip()[:200]
            pairs.append((hyp_text, ev_text, True))

    if not pairs:
        return []

    # Build NLI input list: (premise=evidence, hypothesis=claim/adversarial)
    nli_inputs = [(ev_text, hyp) for hyp, ev_text, _ in pairs]

    # Batch inference — run synchronous NLI in executor so it doesn't
    # block the async event loop (fixes 200s+ latency on CPU inference).
    loop = asyncio.get_event_loop()
    nli_results = await loop.run_in_executor(None, hub.nli.predict_batch, nli_inputs)

    rows: List[MatrixRow] = []
    for (hyp_text, ev_text, is_adv), nli in zip(pairs, nli_results):
        rows.append(MatrixRow(
            hypothesis=hyp_text,
            evidence_text=ev_text,
            entailment=nli.entailment,
            contradiction=nli.contradiction,
            neutral=nli.neutral,
            is_adversarial=is_adv,
            claim_text=claim_text,
        ))

    return rows
